MVCProject/ProductMvcProject/Controllers/UserDashboardController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using ProductMvcProject.Context;
using ProductMvcProject.Exception;
using ProductMvcProject.Models;
using ProductMvcProject.Service;
using System.Text.Json;

namespace ProductMvcProject.Controllers
{
    public class UserDashboardController : Controller

    {
        Product_DbContext _productdbcontext;
        readonly IProductService _productservice;
        //readonly Product_DbContext _product_Db;
        public UserDashboardController(IProductService productService, Product_DbContext product_DbContext)
        {
           _productservice = productService;
            _productdbcontext = product_DbContext;  
        }
        [Authorize]
        //public IActionResult Index()

        //{

        //    return View();
        //}
        [Authorize]
        public ActionResult ViewProduct()


        {
            IEnumerable<ProductDb> products = _productservice.ViewProduct();
            return View(products);
            

        }
        public ActionResult AddTocart(int id,ProductDb product)
        {
            try
            {

                int UserID = (int)HttpContext.Session.GetInt32("UseId");
                _productservice.AddToCart(id, UserID);
                TempData["success"] = "Added Succefully To the cart";
                return RedirectToAction("ViewProduct");
            }
            catch(CartAlreadyExists caie)
            {
                TempData["error"] = caie.Message;
                return RedirectToAction("ViewProduct");
            }
           
                
            
            
        }

        public ActionResult Viewcart()
        {
            int UserID = (int)HttpContext.Session.GetInt32("UseId");
            List<ShoppingCart> cart = _productservice.Viewcart(UserID);
            return View(cart);
        }
        public ActionResult DeleteFromCart(int id)
        {
            _productservice.DeleteFromCart(id);
            return RedirectToAction("Viewcart");
        }
        public ActionResult CheckOut()
        {
            int UserID = (int)HttpContext.Session.GetInt32("UseId");
            List<ShoppingCart> cart = _productservice.Viewcart(UserID);
            string InvoiceNo = Guid.NewGuid().ToString();
            List<Order> order = new List<Order>();
            cart.ForEach(item =>
            {
                order.Add(new Order()
                {
                    ProductID = item.ProductID,
                    ProductName = item.ProductName,
                    Invoice = InvoiceNo,
                    UserID=item.UserID,
                    Quantity=item.Quantity,
                    Price=item.Price*item.Quantity,
                    Status="Ordered"



                });
            });
            int total = 0;
            foreach(Order item in order)
            {
                total +=(int)item.Price;
                
            }
            TempData["total"] =total;
            bool res = _productservice.AddOrder(order);
            if (res == true)
            {
                _productservice.DeleteFromCart(cart);

            }
            return RedirectToAction("ViewOrder");
        }
        public IActionResult ViewOrder()
        {
            int UserID = (int)HttpContext.Session.GetInt32("UseId");
            var  order = _productservice.ViewOrder(UserID).DistinctBy(item => item.Invoice).ToList();

            return View(order);
        }

        public ActionResult Addcartitem(int id)
        {
           
            ShoppingCart cart=_productdbcontext.CartTbl.FirstOrDefault(u=>u.CartID== id);
            cart.Quantity += 1;
            _productdbcontext.Entry<ShoppingCart>(cart).State = Microsoft.EntityFrameworkCore.EntityState.Modified;
            _productdbcontext.SaveChanges();
            return RedirectToAction("Viewcart");

        }
        public ActionResult Subcartitem(int id)
        {
            ShoppingCart cart = _productdbcontext.CartTbl.FirstOrDefault(u => u.CartID == id);
            if (cart.Quantity > 1)
            {
                cart.Quantity -= 1;
                _productdbcontext.Entry<ShoppingCart>(cart).State = Microsoft.EntityFrameworkCore.EntityState.Modified;
                _productdbcontext.SaveChanges();
                return RedirectToAction("Viewcart");
            }
            else
            {
                return RedirectToAction("Viewcart");
            }
            

        }
        [HttpGet]
        public IActionResult ViewOrderDetails(string id)
        {
            int UserID = (int)HttpContext.Session.GetInt32("UseId");
           
            if (UserID != null)
            {
                //ViewBag.User = user;
            }
            else
            {
                return RedirectToRoute(new { controller = "User", action = "Login" });
            }
            var olist =_productservice.ViewOrder(UserID).Where(item => item.Invoice == id).ToList();
            
            ViewBag.Invoice = id;
            double orderTotal = 0;
            olist.ForEach(o =>
            {
                orderTotal += o.Quantity * o.Price;
            });
            ViewBag.OrderTotal = orderTotal;
            return View(olist);
        }



    }
}

MVCProject/ProductMvcProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProductMvcProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProductMvcProject.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Productocity</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Login">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Register">Register</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ProductMvcProject - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MVCProject/ProductMvcProject/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProductMvcProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProductMvcProject.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
               @* <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Productocity</a>*@
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/Images/logo4.png" height="100px" width="100px" /></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="AdminDashboard" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="AdminDashboard" asp-action="Index">Product</a>
                        </li>
                    </ul>
                </div>
            </div>
             @if (User.Identity.IsAuthenticated)
            {
                <div class="navbar float-none">
                    <span class=" text-success font-weight-bold p-2">Welcome @User.Identity.Name.ToUpper()</span>
                    <a class=" btn btn-sm btn-danger" 
                    asp-action="Logout" asp-controller="User">LogOut</a>
                </div>
            }
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Productocity  
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MVCProject/ProductMvcProject/Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProductMvcProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProductMvcProject.styles.css" asp-append-version="true" />
</head>
<body>
    
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Productocity 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MVCProject/ProductMvcProject/Views/Shared/_LayoutRegister.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProductMvcProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProductMvcProject.styles.css" asp-append-version="true" />
</head>
<body>
    
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ProductMvcProject - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MVCProject/ProductMvcProject/Views/Shared/_Layoutuserdashoboard.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProductMvcProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" />
    
   
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProductMvcProject.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                @*<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Productocity</a>*@
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/Images/logo4.png" height="100px" width="100px" /></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="UserDashboard" asp-action="Index">Home</a>
                        </li>*@
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="UserDashboard" asp-action="ViewProduct">View Product</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="UserDashboard" asp-action="Viewcart">View Cart</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="UserDashboard" asp-action="ViewOrder">View Order</a>
                        </li>
                        
                    </ul>
                </div>
            </div>
            @if (User.Identity.IsAuthenticated)
            {
                <div class="navbar float-none">
                    <span class=" text-success font-weight-bold p-2">Welcome @User.Identity.Name.ToUpper()</span>
                    <a class=" btn btn-sm btn-danger" 
                    asp-action="Logout" asp-controller="User">LogOut</a>
                </div>
            }
        </nav>
    </header>
   

    <div class="container">
        <main role="main" class="pb-3">
            

            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Productocity -
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>